/**
 * Bundles `src/` into an Apps Script project in `outDir` (Solution Design §11).
 *
 * `outDir/Code.js` is one esbuild IIFE that assigns its exports to the global
 * `JevGmailClassifier`, followed by a generated footer of top-level `function`
 * declarations, one per entry point: triggers and the editor only see
 * declarations. `outDir/appsscript.json` is a byte-for-byte copy of the
 * repo-root manifest. The caller passes the validated config, which is served
 * to `src/entry/` as the module `virtual:generated-config`.
 *
 * `scripts/build.ts` is the CLI. The bundle test calls `bundle()` directly.
 */
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';

import { build, type Plugin } from 'esbuild';

import { ENTRY_POINTS } from '../src/entry/entry-points.ts';
import { GENERATED_CONFIG_SPECIFIER, generatedConfigModule } from './generated-config.ts';

/**
 * The ECMAScript version the bundle targets. Apps Script's V8 version isn't
 * published: raise this only with evidence from a spike (SD §11), together
 * with `lib` in `tsconfig.json`.
 */
export const ECMA_VERSION = 2020;
export const ESBUILD_TARGET = `es${String(ECMA_VERSION)}`;
export const GLOBAL_NAME = 'JevGmailClassifier';

export const REPO_ROOT = resolve(import.meta.dirname, '..');

const ENTRY_FILE = join(REPO_ROOT, 'src', 'entry', 'main.ts');
const MANIFEST_FILE = join(REPO_ROOT, 'appsscript.json');
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export interface BundleOptions {
  /** The output directory, relative to the repo root or absolute. It is emptied first. */
  readonly outDir: string;
  /**
   * The raw, already validated config data. It is embedded as the module
   * `virtual:generated-config`, served from memory: `bundle()` never reads
   * `src/generated/`.
   */
  readonly embeddedConfig: unknown;
  /** Where the config came from, for the generated module's header comment. */
  readonly configSourceName?: string;
}

/** The global-function footer: a comment line, then one line per name, in order. */
export function renderFooter(names: readonly string[]): string {
  const lines = names.map((name) => {
    if (!IDENTIFIER.test(name)) {
      throw new Error(`Entry point name is not a JavaScript identifier: ${JSON.stringify(name)}`);
    }
    return `function ${name}() { return ${GLOBAL_NAME}.${name}(); }`;
  });
  return ['// Global functions generated by scripts/bundle.ts. Do not edit.', ...lines, ''].join(
    '\n',
  );
}

/**
 * Resolves `outDir` against the repo root, and refuses the repo root itself or
 * any directory that contains it, because `bundle()` empties `outDir`.
 */
export function resolveOutDir(outDir: string): string {
  const resolved = resolve(REPO_ROOT, outDir);
  const fromOutDirToRoot = relative(resolved, REPO_ROOT);
  if (!fromOutDirToRoot.startsWith('..')) {
    throw new Error(`Refusing to empty ${resolved}: it is or contains the repository root`);
  }
  return resolved;
}

/** Resolves `virtual:generated-config` to the generated module, served from memory. */
export function generatedConfigPlugin(embeddedConfig: unknown, sourceName: string): Plugin {
  const namespace = 'generated-config';
  // Render now, so data that can't be embedded fails before anything is bundled.
  const contents = generatedConfigModule(embeddedConfig, sourceName);
  const filter = new RegExp(`^${GENERATED_CONFIG_SPECIFIER}$`);
  return {
    name: namespace,
    setup(pluginBuild) {
      pluginBuild.onResolve({ filter }, (args) => ({ path: args.path, namespace }));
      pluginBuild.onLoad({ filter: /.*/, namespace }, () => ({
        contents,
        loader: 'ts',
        resolveDir: REPO_ROOT,
      }));
    },
  };
}

export async function bundle({
  outDir,
  embeddedConfig,
  configSourceName = 'config.yaml',
}: BundleOptions): Promise<void> {
  const configPlugin = generatedConfigPlugin(embeddedConfig, configSourceName);
  const dir = resolveOutDir(outDir);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });

  const codeFile = join(dir, 'Code.js');
  const result = await build({
    absWorkingDir: REPO_ROOT,
    entryPoints: [ENTRY_FILE],
    outfile: codeFile,
    bundle: true,
    format: 'iife',
    globalName: GLOBAL_NAME,
    target: ESBUILD_TARGET,
    // `neutral`: a Node built-in import fails the build instead of being shimmed.
    // If a dependency fails to resolve, set `mainFields: ['module', 'main']`
    // rather than switching to `node`.
    platform: 'neutral',
    // Readable stack traces in the Apps Script editor.
    minify: false,
    sourcemap: false,
    write: false,
    plugins: [configPlugin],
  });

  const [output, ...extra] = result.outputFiles;
  if (output === undefined || extra.length > 0) {
    throw new Error(`esbuild produced ${String(result.outputFiles.length)} files; expected 1`);
  }

  writeFileSync(codeFile, `${output.text}\n${renderFooter(ENTRY_POINTS)}`);
  copyFileSync(MANIFEST_FILE, join(dir, 'appsscript.json'));
}
