/**
 * The generated config module (Solution Design §11).
 *
 * Source code reaches the embedded config only through the virtual specifier
 * `virtual:generated-config`, imported by `src/entry/` alone. `bundle()`
 * serves the module from memory, so `typecheck`, `lint` and `test` never need
 * `src/generated/` or a `config.yaml`. `scripts/build.ts` also writes the same
 * text to `src/generated/config.ts`, so a developer can see what was embedded.
 */
import { isDeepStrictEqual } from 'node:util';

/** The specifier `src/entry/` imports. Declared in `src/entry/generated-config.d.ts`. */
export const GENERATED_CONFIG_SPECIFIER = 'virtual:generated-config';

/** Where the build writes a copy of the module, relative to the repo root. Git-ignored. */
export const GENERATED_CONFIG_FILE = 'src/generated/config.ts';

/**
 * The module text: the raw, already validated YAML data as a JSON literal,
 * typed `unknown` so every reader goes through the runtime loader (#43),
 * which parses it again with the same schema.
 *
 * Throws if the data doesn't survive a JSON round trip (for example
 * `Infinity`, `undefined` or a `Date`): the schema rejects such values, so
 * reaching this is invalid state.
 */
export function generatedConfigModule(raw: unknown, sourceName: string): string {
  const json = JSON.stringify(raw, null, 2);
  if (typeof json !== 'string' || !isDeepStrictEqual(JSON.parse(json), raw)) {
    throw new Error(`The config from ${sourceName} can't be embedded as JSON`);
  }
  const source = sourceName.replace(/[\r\n]+/g, ' ');
  return [
    `// Generated by scripts/build.ts from ${source}. Do not edit.`,
    `export const EMBEDDED_CONFIG: unknown = ${json};`,
    '',
  ].join('\n');
}
