import { describe, expect, it } from 'vitest';

import { generatedConfigModule } from '../../scripts/generated-config.ts';

describe('generatedConfigModule', () => {
  it('embeds the raw data as a JSON literal typed unknown, under a header', () => {
    const raw = { defaultThreshold: 0.8, rules: [{ id: 'bill', question: 'Q?', label: 'Bill' }] };
    expect(generatedConfigModule(raw, 'config.yaml')).toBe(
      [
        '// Generated by scripts/build.ts from config.yaml. Do not edit.',
        `export const EMBEDDED_CONFIG: unknown = ${JSON.stringify(raw, null, 2)};`,
        '',
      ].join('\n'),
    );
  });

  it('keeps the header on one line whatever the source name', () => {
    const text = generatedConfigModule({}, 'odd\nname.yaml');
    expect(text.split('\n')[0]).toBe(
      '// Generated by scripts/build.ts from odd name.yaml. Do not edit.',
    );
  });

  it.each([
    ['Infinity', { dailyTokenBudget: Number.POSITIVE_INFINITY }],
    ['undefined', { excludeQuery: undefined }],
    ['a Date', { when: new Date(0) }],
  ])('refuses data JSON cannot carry exactly (%s)', (_, raw) => {
    expect(() => generatedConfigModule(raw, 'c.yaml')).toThrow(/can't be embedded as JSON/);
  });
});
